name: flutter_msal_platform_interface
description: A common platform interface for the flutter_msal plugin.
version: 0.0.3
repository: https://github.com/along-comet/pbs_flutter_package_login
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  meta: ^1.7.0
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
